version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

      
  auth:
    build: ./auth-service
    environment:
      APP_URL: http://auth:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: company_auth_db
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8005:8000"

  department:
    build: ./department-service
    depends_on:
      - auth
    environment:
      APP_URL: http://department:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: company_department_db
      DB_USERNAME: root
      DB_PASSWORD: root
      AUTH_SERVICE_URL: http://auth:8000
    ports:
      - "8001:8000"

  position:
    build: ./position-service
    depends_on:
      - auth
    environment:
      APP_URL: http://position:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: company_position_db
      DB_USERNAME: root
      DB_PASSWORD: root
      AUTH_SERVICE_URL: http://auth:8000
    ports:
      - "8003:8000"

  employee:
    build: ./employee-service
    depends_on:
      - auth
      - department
      - position
    environment:
      APP_URL: http://employee:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: company_employee_db
      DB_USERNAME: root
      DB_PASSWORD: root
      AUTH_SERVICE_URL: http://auth:8000
      DEPARTMENT_SERVICE_URL: http://department:8000
      POSITION_SERVICE_URL: http://position:8000
    ports:
      - "8002:8000"

  salary:
    build: ./salary-service
    depends_on:
      - auth
      - employee
    environment:
      APP_URL: http://salary:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: company_salary_db
      DB_USERNAME: root
      DB_PASSWORD: root
      AUTH_SERVICE_URL: http://auth:8000
      EMPLOYEE_SERVICE_URL: http://employee:8000
    ports:
      - "8004:8000"

  gateway:
    build: ./gateway-service
    depends_on:
      - auth
      - department
      - employee
      - position
      - salary
    environment:
      APP_URL: http://gateway:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: company_gateway_db
      DB_USERNAME: root
      DB_PASSWORD: root
      AUTH_SERVICE_URL: http://auth:8000
      EMPLOYEE_SERVICE_URL: http://employee:8000
      DEPARTMENT_SERVICE_URL: http://department:8000
      POSITION_SERVICE_URL: http://position:8000
      SALARY_SERVICE_URL: http://salary:8000
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      VITE_AUTH_API_URL: http://127.0.0.1:8005/api
      VITE_GATEWAY_API_URL: http://127.0.0.1:8000/api
    ports:
      - "5173:5173"