apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
        - name: department
          image: abdelilahmo/department-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "mysql"
            - name: DB_DATABASE
              value: "company_department_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: department
spec:
  selector:
    app: department
  ports:
    - port: 8000
      targetPort: 8000