apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: abdelilahmo/employee-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_CONNECTION
              value: "mysql"  
            - name: DB_HOST
              value: "mysql"
            - name: DB_DATABASE
              value: "company_employee_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: employee
spec:
  selector:
    app: employee
  ports:
    - port: 8000
      targetPort: 8000