apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: abdelilahmo/frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_AUTH_API_URL
              value: "http://localhost:30005/api"
            - name: VITE_GATEWAY_API_URL
              value: "http://localhost:30000/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30010
  type: NodePort