apiVersion: apps/v1
kind: Deployment
metadata:
  name: position
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position
  template:
    metadata:
      labels:
        app: position
    spec:
      containers:
        - name: position
          image: abdelilahmo/position-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "mysql"
            - name: DB_DATABASE
              value: "company_position_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: position
spec:
  selector:
    app: position
  ports:
    - port: 8000
      targetPort: 8000