apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salary
  template:
    metadata:
      labels:
        app: salary
    spec:
      containers:
        - name: salary
          image: abdelilahmo/salary-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_CONNECTION
              value: "mysql"  
            - name: DB_HOST
              value: "mysql"
            - name: DB_DATABASE
              value: "company_salary_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: AUTH_SERVICE_URL
              value: "http://auth:8000"
            - name: EMPLOYEE_SERVICE_URL
              value: "http://employee:8000"
          command: ["sh", "-c"]
          args:
            - php artisan config:clear && php artisan cache:clear && php artisan config:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000
---
apiVersion: v1
kind: Service
metadata:
  name: salary
spec:
  selector:
    app: salary
  ports:
    - port: 8000
      targetPort: 8000
