apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salary
  template:
    metadata:
      labels:
        app: salary
    spec:
      containers:
        - name: salary
          image: abdelilahmo/salary-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_CONNECTION
              value: "mysql"  
            - name: DB_HOST
              value: "mysql"
            - name: DB_DATABASE
              value: "company_salary_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: salary
spec:
  selector:
    app: salary
  ports:
    - port: 8000
      targetPort: 8000