name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Auth
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          push: true
          tags: abdelilahmo/auth-service:latest

      - name: Build & Push Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./gateway-service
          push: true
          tags: abdelilahmo/gateway-service:latest